CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START 1;
CREATE TABLE IF NOT EXISTS clients
(
    id BIGSERIAL PRIMARY KEY ,
    name VARCHAR(200) NOT NULL ,
    email VARCHAR(254) NOT NULL ,
    phone VARCHAR(20) NOT NULL
);